"""新增 Users 的 profile 欄位

Revision ID: 590abe1b183e
Revises: 
Create Date: 2023-01-27 14:04:09.668363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590abe1b183e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile')
    # ### end Alembic commands ###
